// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGREMf_-5OOiUZGWYDPhydxP8p3sowIiA',
    appId: '1:72533694684:web:88e7a0806e0f583ffc3c19',
    messagingSenderId: '72533694684',
    projectId: 'content-management-library',
    authDomain: 'content-management-library.firebaseapp.com',
    storageBucket: 'content-management-library.appspot.com',
    measurementId: 'G-4B6DW1ZFHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3nG_5bNLAadhGo0IhTq85q8IyCUh1qqs',
    appId: '1:72533694684:android:b8af2844ba3c258afc3c19',
    messagingSenderId: '72533694684',
    projectId: 'content-management-library',
    storageBucket: 'content-management-library.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIii31Dd9pEHNPUoBsqyTjOVgI_xMXzvg',
    appId: '1:72533694684:ios:f46e3c32687d7a76fc3c19',
    messagingSenderId: '72533694684',
    projectId: 'content-management-library',
    storageBucket: 'content-management-library.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIii31Dd9pEHNPUoBsqyTjOVgI_xMXzvg',
    appId: '1:72533694684:ios:6a6835c1e16883bafc3c19',
    messagingSenderId: '72533694684',
    projectId: 'content-management-library',
    storageBucket: 'content-management-library.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
